Repository Guidesu/Frozen-Summits, pull requests merged in 2024-12, with the labels that each got.

#21 Fixed Barbarian Adventurer Class
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/barbarian.dm
  code/modules/mob/living/simple_animal/rogue/creacher/mole.dm
Labels: Balance

#23 Eastern Weapon Addition
  code/game/objects/items/rogueweapons/melee/blunt.dm
  code/game/objects/items/rogueweapons/melee/flail.dm
  code/game/objects/items/rogueweapons/melee/knives.dm
  code/game/objects/items/rogueweapons/melee/polearms.dm
  code/game/objects/items/rogueweapons/melee/swords.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
  icons/roguetown/weapons/32.dmi
  icons/roguetown/weapons/64.dmi
Labels: Spriting

#27 Fixed the FF mercs belt
  code/modules/jobs/job_types/roguetown/mercenaries/classes/condottiero.dm
Labels: Balance

#32 Guns for dwarves (and merc fixes)
  code/modules/jobs/job_types/roguetown/mercenaries/classes/grenzelhoft.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/underdweller.dm
Labels: Balance

#31 Gun mercenary , more Zhentarim
  code/modules/jobs/job_types/roguetown/mercenaries/classes/condottiero.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/desertrider.dm
Labels: Balance

#33 underdweller backpack fix because rogue-code is idiotic
  code/modules/jobs/job_types/roguetown/mercenaries/classes/underdweller.dm
Labels: Balance

#34 The good stuff
  code/game/objects/items/rogueitems/painting.dm
  code/modules/cargo/packsrogue/tools.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/condottiero.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/desertrider.dm
  code/modules/roguetown/roguemachine/ATM.dm
  code/modules/roguetown/roguemachine/merchant.dm
  code/modules/roguetown/roguemachine/steward.dm
Labels: Balance

#36 More renaming
  code/game/objects/items/rogueitems/bait.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  code/modules/mob/living/carbon/human/npc/searaider.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/goose.dm
Labels: Balance

#38 Update heartfelt wave.dm
  code/datums/migrants/migrant_waves/fablefield roles.dm
  code/datums/migrants/migrant_waves/fablefield wave.dm
  code/datums/migrants/migrant_waves/heartfelt wave.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/heartfelt.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/heartfelthand.dm
Labels: Balance

#40 Lore & jobs
  code/datums/migrants/migrant_waves/heartfelt roles.dm
  code/datums/special_traits/traits/traits.dm
  code/game/objects/structures/roguetown/telescope.dm
  code/modules/jobs/job_types/roguetown/yeomen/artificer.dm
Labels: Balance

#43 Merc rework
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/cloaks.dm
  code/modules/clothing/rogueclothes/gloves.dm
  code/modules/clothing/rogueclothes/pants.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/forlorn.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/grenzelhoft.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/routier.dm
Labels: Balance

#47 Dev
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#53 QoL changes
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#54 Hobo hut
  _maps/map_files/dun_manor/azure_coast.dmm
Labels: Mapping

#55 Bunk house, spades and fireplaces OH MY!!
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#57 Ports over Planks/Stone block crafting mechanics
  code/datums/components/crafting/crafting.dm
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/rogueitems/natural/glass.dm
  code/game/objects/items/rogueitems/natural/stones.dm
  code/game/objects/items/rogueitems/natural/wood.dm
  code/game/objects/structures/beds_chairs/roguechair.dm
  code/game/objects/structures/roguewindow.dm
  code/modules/cargo/packsrogue/rawmat.dm
  code/modules/cargo/packsrogue/tools.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/carpenter.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/rare/Lmason.dm
  code/modules/roguetown/roguecrafting/items.dm
  code/modules/roguetown/roguecrafting/structure.dm
  code/modules/roguetown/roguecrafting/turfs.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/_anvil_recipe.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/tools.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
  code/modules/roguetown/roguejobs/craftsman/tools.dm
  code/modules/roguetown/roguestock/import.dm
  icons/roguetown/items/crafting.dmi
  icons/roguetown/items/natural.dmi
  icons/roguetown/weapons/64.dmi
  roguetown.dme
  sound/items/sawing.ogg
  sound/items/wood_cutting.ogg
Labels: Balance, Spriting
