Repository Guidesu/Frozen-Summits, pull requests merged in 2025-02, with the labels that each got.

#145 Big spooky slimey dungeon with suprise!
  _maps/map_files/dun_manor/dakkaswamp.dmm
Labels: Mapping

#149 QoL requests added
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#150 Saiga spawners removed
  _maps/map_files/dun_manor/azure_forest.dmm
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#152 Dungeon fix and additions
  _maps/map_files/dun_manor/dakkaswamp.dmm
Labels: Mapping

#155 Map request from techie
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#157 QoL change in forest
  _maps/map_files/dun_manor/azure_forest.dmm
Labels: Mapping

#159 Okay for real this time, goblin hut for flint. (techie request)
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#154 Extra Alchemy Additions
  code/modules/roguetown/roguecrafting/alchemy.dm
  code/modules/roguetown/roguecrafting/alchemy/cauldron_recipes.dm
  code/modules/roguetown/roguecrafting/alchemy/grind_recipes.dm
  code/modules/roguetown/roguecrafting/alchemy/ingredients.dm
  icons/roguetown/misc/alchemy.dmi
Labels: Spriting

#210 Renames a Lot of Things and Re-Adds Adamantine/Blacksteel Recipe
  code/__DEFINES/traits.dm
  code/__HELPERS/time.dm
  code/datums/skills/craft.dm
  code/datums/status_effects/rogue/roguebuff.dm
  code/game/objects/items/granters.dm
  code/game/objects/items/rogueitems/books.dm
  code/game/objects/items/rogueitems/devices.dm
  code/game/objects/items/rogueitems/gems.dm
  code/game/objects/items/rogueweapons/melee/swords.dm
  code/game/objects/structures/fluff.dm
  code/modules/cargo/packsrogue/Mage.dm
  code/modules/clothing/rogueclothes/rings.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/warscholar.dm
  code/modules/roguetown/roguecrafting/alchemy.dm
  code/modules/roguetown/roguecrafting/alchemy/alch_items.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/valuables.dm
  code/modules/roguetown/roguejobs/blacksmith/smelter.dm
  code/modules/roguetown/roguejobs/miner/rogueores.dm
  code/modules/roguetown/roguemachine/scomm.dm
  code/modules/underworld/underworld.dm
  icons/roguetown/items/ore.dmi
  icons/roguetown/misc/alchemy.dmi
  icons/roguetown/misc/herbfoliage.dmi
  modular/Neu_Food/code/raw/NeuFood_dough.dm
  modular_azurepeak/code/game/objects/items/spellbooks.dm
  modular_azurepeak/code/modules/spells/pantheon/inhumen/zizo.dm
  modular_azurepeak/code/modules/spells/warscholar.dm
  modular_azurepeak/virtues/combat.dm
  modular_hearthstone/code/game/objects/structures/longsleep.dm
  modular_hearthstone/code/modules/spells/roguetown/wizard.dm
  strings/accent_universal.json
  strings/books/law.json
  strings/books/law_2.json
  strings/books/tales6.json
Labels: content, lore fixing

#216 Fixes Some Sizes and Ore Generation, Adds Trees to South East
  _maps/map_files/dun_manor/dun_manor.dmm
  code/game/objects/items/rogueitems/bombs.dm
  code/game/objects/items/rogueitems/gems.dm
  code/game/objects/items/rogueitems/natural/stones.dm
  code/game/objects/items/toys.dm
  code/game/turfs/closed/minerals.dm
  code/modules/roguetown/roguejobs/blacksmith/smelter.dm
  code/modules/surgery/bodyparts/head.dm
Labels: bugfixing, general fixes

#215 Removal of Roguetown Mentions
  code/datums/gods/patrons/inhumen_pantheon.dm
  code/datums/special_traits/traits/traits.dm
  code/game/area/roguetownareas.dm
  code/game/gamemodes/objective.dm
  code/game/objects/items/rogueweapons/melee/knives.dm
  code/game/objects/items/rogueweapons/melee/swords.dm
  code/game/objects/structures/roguetown/bell.dm
  code/game/objects/structures/roguetown/handcart.dm
  code/game/turfs/open/lava.dm
  code/modules/antagonists/roguetown/villain/ascendant/ascendant.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/cloaks.dm
  code/modules/clothing/rogueclothes/feet.dm
  code/modules/clothing/rogueclothes/gloves.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/mask.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/clothing/rogueclothes/pants.dm
  code/modules/clothing/rogueclothes/shirts.dm
  code/modules/clothing/rogueclothes/wrists.dm
  code/modules/jobs/job_types/roguetown/Inquisition/puritan.dm
  code/modules/jobs/job_types/roguetown/garrison/sergeant.dm
  code/modules/jobs/job_types/roguetown/youngfolk/orphan.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/roguetown/roguemachine/lottery.dm
  code/modules/shuttle/emergency.dm
  config/example/config.txt
  config/example/motd.txt
  modular_azurepeak/code/game/objects/items/mundanities.dm
  modular_azurepeak/code/game/objects/items/quicksilver.dm
  strings/abyssal_replacement.json
  strings/phobia.json
  strings/rt/bumlines.txt
Labels: Lore Fixes, General Fixes
