Repository Guidesu/Frozen-Summits, pull requests merged in 2025-01, with the labels that each got.

#59 New world
  _maps/map_files/dun_manor/azure_coast.dmm
  _maps/map_files/dun_manor/dun_manor.dmm
  _maps/map_files/dun_manor/smalldecap.dmm
  _maps/map_files/dun_manor/smallforest.dmm
  code/game/objects/structures/roguetown/rogueflora.dm
  icons/roguetown/misc/96x96.dmi
Labels: Spriting, Mapping

#60 Extends the Underswamp a bit and adds a new house
  _maps/map_files/dun_manor/azure_coast.dmm
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#62 Mount decap update
  _maps/map_files/dun_manor/smalldecap.dmm
Labels: Mapping

#64 North Tavern/inn, walkway and wine cellar
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#65 Decapmountain V2 update
  _maps/map_files/dun_manor/smalldecap.dmm
Labels: Mapping

#69 Decapmountain v2 fix
  _maps/map_files/dun_manor/smalldecap.dmm
Labels: Mapping

#68 Central Tavern/Inn Overhaul
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#67 Engineering recipe, artificer stat fix
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/donator/vaquero.dm
  code/modules/jobs/job_types/roguetown/yeomen/artificer.dm
  code/modules/roguetown/roguejobs/engineer/anvil_recipes/mechanical.dm
Labels: Balance

#72 Some walls and small changes to the hamlet
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#73 Yet another renaming patch
  _maps/map_files/dun_manor/azure_coast.dmm
  modular_guidesa/turfs.dm
Labels: Mapping

#75 Jail added
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#76 Outer Gates Reflavor & Inn Tweaking
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#79 Waltuh
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#80 Adds more to the underground and above ground
  _maps/map_files/dun_manor/azure_coast.dmm
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#83 Flavor changes and small QoL
  _maps/map_files/dun_manor/azure_coast.dmm
  _maps/map_files/dun_manor/azure_forest.dmm
  _maps/map_files/dun_manor/dun_manor.dmm
  _maps/map_files/dun_manor/smalldecap.dmm
Labels: Mapping

#84 Vineyard Updatening
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#86 Small changes, fixes and personal requests.
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#87 Massive update to map (GOOD to MERGE)
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#90 asdf
  code/modules/jobs/job_types/roguetown/church/druid.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Labels: Balance

#92 Small changes
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#97 New house and removing things from house two
  _maps/map_files/dun_manor/azure_forest.dmm
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#98 Jacks house, door keys and locks oh my
  _maps/map_files/dun_manor/azure_forest.dmm
Labels: Mapping

#99 WINDOWS FIXED?! maybe
  _maps/map_files/dun_manor/azure_forest.dmm
Labels: Mapping

#100 Incorrect key id for treehut lock
  _maps/map_files/dun_manor/azure_forest.dmm
Labels: Mapping

#103 Fixed some mercenary classes and lore-weirdness.
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/desertrider.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/warscholar.dm
  code/modules/roguetown/roguemachine/scomm.dm
Labels: Balance

#105 Keiran/Jeri Home Addition
  _maps/map_files/dun_manor/azure_forest.dmm
Labels: Mapping

#110 Ninja house
  _maps/map_files/dun_manor/azure_forest.dmm
Labels: Mapping

#111 Shadow cursed edit/mapfixes
  _maps/map_files/dun_manor/azure_forest.dmm
  _maps/map_files/dun_manor/dakkaswamp.dmm
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#117 Small fixes to the main town map
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#123 buffed mercs
  code/modules/jobs/job_types/roguetown/mercenaries/classes/desertrider.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/warscholar.dm
Labels: Balance

#119 Forest tweaks
  _maps/map_files/dun_manor/azure_forest.dmm
Labels: Mapping

#136 Fixed my whoopsie
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#138 Small changes
  _maps/map_files/dun_manor/azure_forest.dmm
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#140 RAAAAAA!! ANOTHER FIX!! RAAA!!
  _maps/map_files/dun_manor/dun_manor.dmm
Labels: Mapping

#141 Excess Removal
  _maps/map_files/dun_manor/azure_forest.dmm
Labels: Mapping

#143 Content addition
  _maps/map_files/dun_manor/azure_forest.dmm
Labels: Mapping
